In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm 

In [4]:
X,y = datasets.load_iris(return_X_y=True)
print(X.shape,y.shape)

(150, 4) (150,)


In [ ]:
print(y)

In [ ]:
X

In [7]:
from sklearn.model_selection import cross_val_score

In [8]:
clf = svm.SVC(kernel='linear',C=1,random_state=0)  # lr = LinearRegression()

In [9]:
score = cross_val_score(clf,X,y,cv=5)

In [10]:
score

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [12]:
score.mean()

0.9800000000000001

In [13]:
score.std()

0.016329931618554516

In [19]:
#other method for fold
from sklearn.model_selection import ShuffleSplit
n_splits = X.shape[0] #no of rows 
cv = ShuffleSplit(n_splits=5 ,test_size = 0.2,random_state = 0)
(cross_val_score(clf,X,y,cv=cv)).mean()

0.9933333333333334

In [ ]:
#leave one out

In [23]:
from sklearn.model_selection import LeaveOneOut
x = [10,20,30,40,50,60,70,80,90,100]
l = LeaveOneOut()

In [24]:
for train,test in l.split(x):
  print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [29]:
from sklearn.model_selection import LeavePOut
l1 = LeavePOut(p=2)
for train,test in l1.split(x):
  print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8

In [35]:
#Stratified cross validation
x  = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
y = np.array([0,0,1,0,1,1])
print(x.shape)
print(y.shape)

(6, 2)
(6,)


In [33]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3,random_state = None,shuffle = False)

In [37]:
for train_index,test_index in skf.split(x,y):
  x_train,y_train = x[train_index],y[train_index]
  x_test,y_test = x[test_index],y[test_index]

In [38]:
x_train

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 9, 10]])

In [39]:
y_train

array([0, 0, 1, 1])

In [40]:
x_test

array([[ 7,  8],
       [11, 12]])

In [41]:
y_test

array([0, 1])