In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [22]:
data=pd.read_csv("/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv")

In [23]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [24]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [25]:
#find and deal with missing data.
from sklearn.impute import SimpleImputer
Imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
Imputer.fit(X[:, 1:3])
X[:,1:3]=Imputer.transform(X[:,1:3])

In [26]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [27]:
#Handle categorical datapoints
#for independant variable datapoints
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y= le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [32]:
#Features Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X[:,3:]=sc.fit_transform(X[:,3:])



In [33]:
X

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [43]:
import numpy as np

def GD(X,y):
  cur_m=0
  cur_b=0
  iter=500
  lr=0.0005
  n=len(X)
  for i in range(iter):
    y_pred=cur_b+X*cur_m
    cost=(1/n)*sum([ val**2 for val in (y-y_pred)])
    md = -(2/n)*sum(X*(y-y_pred))
    bd = -(2/n)*sum(y-y_pred)
    cur_m = cur_m-lr*md
    cur_b = cur_b-lr*bd
    print("m {}, b{},cost {},iteration {}".format(cur_m,cur_b,cost,i)) 
X=np.array([1,2,3,4,5])
y=np.array([5,7,9,11,13])
GD(X,y)

m 0.031, b0.009000000000000001,cost 89.0,iteration 0
m 0.061632000000000006, b0.017898000000000004,cost 86.92832600000001,iteration 1
m 0.09190035400000002, b0.026695206000000006,cost 84.905374413284,iteration 2
m 0.12180936448800002, b0.035392809732000007,cost 82.92999919703098,iteration 3
m 0.15136328304943603, b0.04399198882880401,cost 81.0010812655608,iteration 4
m 0.1805663109694058, b0.05249390699082689,cost 79.11752785625016,iteration 5
m 0.20942259982776987, b0.06089971415092785,cost 77.27827191036346,iteration 6
m 0.2379362520872116, b0.0692105466372936,cost 75.4822714684476,iteration 7
m 0.26611132167434043, b0.07742752733439467,cost 73.72850907994852,iteration 8
m 0.2939518145539195, b0.08555176584203726,cost 72.0159912267144,iteration 9
m 0.32146168929630026, b0.09358435863253346,cost 70.34374776005932,iteration 10
m 0.34864485763814335, b0.10152638920601204,cost 68.71083135106834,iteration 11
m 0.37550518503650576, b0.10937892824389159,cost 67.11631695383231,iteration 12
m